/** Accès séparé à la plateforme de gouvernance Schooly. */
import { ArrowRight, CheckCircle2, LockKeyhole, ShieldCheck, School, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { supabase } from "@/lib/supabase";

export default function AdminAccess() {
  const [, setLocation] = useLocation();
  const [access, setAccess] = useState<"checking" | "login" | "forbidden">("checking");
  useEffect(() => { void (async () => { const { data: { user } } = await supabase.auth.getUser(); if (!user) { setAccess("login"); return; } const { data: admin } = await supabase.from("platform_admins").select("user_id").eq("user_id", user.id).eq("status", "active").maybeSingle(); if (admin) { setLocation("/supervision"); return; } setAccess("forbidden"); })(); }, [setLocation]);
  if (access === "checking") return <div className="dashboard-loading">Vérification de l’accès plateforme…</div>;
  if (access === "forbidden") return <main className="admin-access-main admin-access-main--guard"><section><span className="admin-access-badge"><LockKeyhole size={15} /> ACCÈS REFUSÉ</span><h2>Espace réservé<br /><em>à la plateforme</em></h2><p>Votre compte ne dispose pas du rôle super-administrateur Schooly. Vous ne pouvez pas créer ce rôle depuis cette page.</p><button className="admin-access-primary" onClick={() => setLocation("/app")}>Accéder à mon espace <ArrowRight size={17} /></button><button className="admin-access-back" onClick={() => setLocation("/")}>Retourner au site Schooly</button></section></main>;
  return <div className="admin-access-page"><aside className="admin-access-aside"><button className="landing-brand" onClick={() => setLocation("/")}><img src="/manus-storage/schooly-s-mark_1ed993f5.png" alt="" /><span>schooly</span></button><div><p className="landing-eyebrow"><i /> SCHOOLY PLATFORM</p><h1>Votre poste de<br /><em>supervision.</em></h1><p>Un espace réservé à la gouvernance de Schooly. Il ne mélange ni le tableau de bord directeur, ni les données opérationnelles des établissements.</p><div className="admin-access-points"><p><ShieldCheck size={17} /><span><strong>Décisions d’accès</strong><small>Approuver, refuser ou suspendre les établissements.</small></span></p><p><School size={17} /><span><strong>Vision multi-écoles</strong><small>Consulter les demandes et les espaces autorisés.</small></span></p></div></div><Sparkles className="admin-access-sparkle" size={38} /></aside><main className="admin-access-main"><section><span className="admin-access-badge"><LockKeyhole size={15} /> ACCÈS RÉSERVÉ</span><h2>Administration<br /><em>Schooly Platform</em></h2><p>Connectez-vous avec l’adresse e-mail déclarée comme super-administrateur. À la première création de ce compte, le rôle est attribué automatiquement par la base de données.</p><button className="admin-access-primary" onClick={() => setLocation("/connexion?role=platform")}>Accéder à la supervision <ArrowRight size={17} /></button><div className="admin-access-note"><CheckCircle2 size={17} /><p><strong>Vous êtes le propriétaire de la plateforme ?</strong><br />Utilisez votre adresse e-mail propriétaire lors de la première connexion. Vous arriverez directement sur la supervision, pas sur l’espace directeur.</p></div><button className="admin-access-back" onClick={() => setLocation("/")}>Retourner au site Schooly</button></section></main></div>;
}
