import { ArrowUpRight, ChevronRight, FileText, Plus } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { supabase } from "@/lib/supabase";

type RequestStatus = "pending" | "accepted" | "rejected";
type RegistrationRequest = { id: string; candidate_first_name: string; candidate_last_name: string; birth_date: string; gender: "female" | "male" | "other" | "undisclosed" | null; guardian_name: string; guardian_phone: string; requested_class_id: string | null; status: RequestStatus; created_at: string };

const initials = (firstName: string, lastName: string) => `${firstName[0] ?? ""}${lastName[0] ?? ""}`;

export default function Registrations({ schoolId, schoolSlug }: { schoolId: string; schoolSlug: string }) {
  const [requests, setRequests] = useState<RegistrationRequest[]>([]);
  const [loading, setLoading] = useState(true);
  const [processingId, setProcessingId] = useState<string | null>(null);
  const loadRequests = async () => { setLoading(true); const { data, error } = await supabase.from("registration_requests").select("id, candidate_first_name, candidate_last_name, birth_date, gender, guardian_name, guardian_phone, requested_class_id, status, created_at").eq("school_id", schoolId).order("created_at", { ascending: false }); if (error) toast.error("Impossible de charger les demandes", { description: error.message }); else setRequests((data ?? []) as RegistrationRequest[]); setLoading(false); };
  useEffect(() => { void loadRequests(); }, [schoolId]);
  const processRequest = async (request: RegistrationRequest, decision: "accepted" | "rejected") => { setProcessingId(request.id); const { data: { user } } = await supabase.auth.getUser(); if (!user) { setProcessingId(null); return; } if (decision === "accepted") { const studentNumber = `ELV-${new Date().getFullYear()}-${crypto.randomUUID().replace(/-/g, "").slice(0, 7).toUpperCase()}`; const { data: student, error: studentError } = await supabase.from("students").insert({ school_id: schoolId, student_number: studentNumber, first_name: request.candidate_first_name, last_name: request.candidate_last_name, birth_date: request.birth_date, gender: request.gender, guardian_name: request.guardian_name, guardian_phone: request.guardian_phone, status: "active" }).select("id").single(); if (studentError || !student) { setProcessingId(null); toast.error("L’élève n’a pas été créé", { description: studentError?.message }); return; } if (request.requested_class_id) { const { data: classItem } = await supabase.from("classes").select("academic_year_id").eq("id", request.requested_class_id).maybeSingle(); if (classItem?.academic_year_id) await supabase.from("student_enrollments").insert({ school_id: schoolId, student_id: student.id, academic_year_id: classItem.academic_year_id, class_id: request.requested_class_id, status: "enrolled" }); } } const { error } = await supabase.from("registration_requests").update({ status: decision, processed_at: new Date().toISOString(), processed_by: user.id }).eq("id", request.id); setProcessingId(null); if (error) { toast.error("La demande n’a pas été mise à jour", { description: error.message }); return; } await loadRequests(); toast.success(decision === "accepted" ? "Demande acceptée" : "Demande refusée", { description: decision === "accepted" ? "L’élève et son inscription ont été créés." : "La demande a été classée comme refusée." }); };
  const copyLink = () => { void navigator.clipboard.writeText(`${window.location.origin}/inscription/${schoolSlug}`); toast.success("Lien de préinscription copié", { description: "Partagez-le avec les familles de votre établissement." }); };
  const pending = requests.filter((request) => request.status === "pending");
  return <><div className="module-header"><div><p className="eyebrow">GESTION SCOLAIRE</p><h1>Préinscriptions</h1></div><button className="primary-button" onClick={copyLink}><Plus size={17} /> Copier le lien</button></div><section className="module-summary-strip"><div><span>{requests.length}</span><p>demandes reçues</p></div><div><span>{pending.length}</span><p>à examiner</p></div><div><span>{requests.filter((request) => request.status === "accepted").length}</span><p>admissions acceptées</p></div><button className="soft-button" onClick={() => void loadRequests()}>Actualiser les demandes <ArrowUpRight size={16} /></button></section><section className="panel data-panel registration-requests"><div className="panel-heading"><div><p className="eyebrow">DEMANDES EN LIGNE</p><h2>Préinscriptions reçues</h2></div><span className="request-hint">Le lien public est accessible uniquement après approbation de l’établissement.</span></div><div className="student-table"><div className="table-head"><span>CANDIDAT</span><span>TUTEUR</span><span>REÇUE LE</span><span>STATUT</span><span /></div>{requests.map((request) => <div className="table-row registration-request-row" key={request.id}><div className="student-cell"><span className="initial-avatar">{initials(request.candidate_first_name, request.candidate_last_name)}</span><div><strong>{request.candidate_first_name} {request.candidate_last_name}</strong><small>{new Date(request.birth_date).toLocaleDateString("fr-FR")}</small></div></div><span><strong>{request.guardian_name}</strong><small>{request.guardian_phone}</small></span><span>{new Date(request.created_at).toLocaleDateString("fr-FR")}</span><span className={`status-chip ${request.status === "accepted" ? "status-chip--good" : request.status === "rejected" ? "status-chip--watch" : "status-chip--pending"}`}>{request.status === "pending" ? "À examiner" : request.status === "accepted" ? "Acceptée" : "Refusée"}</span><div className="request-actions">{request.status === "pending" ? <><button disabled={processingId === request.id} className="request-accept" onClick={() => void processRequest(request, "accepted")}>Accepter</button><button disabled={processingId === request.id} className="request-reject" onClick={() => void processRequest(request, "rejected")}>Refuser</button></> : <ChevronRight size={18} />}</div></div>)}{!requests.length && <div className="empty-search">{loading ? "Chargement des demandes…" : <><strong>Aucune préinscription reçue.</strong><span>Partagez le lien public avec les familles lorsque votre établissement est approuvé.</span></>}</div>}</div></section><div className="registration-module-link"><FileText size={16} /><span>Lien public : <strong>/inscription/{schoolSlug}</strong></span></div></>;
}
